[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true

[params]
  readingtime = false

[taxonomies]
  tag = "tags"
  author = "authors"

[privacy]
  [privacy.googleAnalytics]
    disable = true

  [privacy.twitter]
    enableDNT = true

  [privacy.vimeo]
    enableDNT = true

  [privacy.youtube]
    privacyEnhanced = true
