markup:
  highlight:
    noClasses: false
    lineNos: true

params:
  faviconICO: favicon.ico
  faviconPNG: favicon.png
  readingtime: true

taxonomies:
  tag: tags
  author: authors
  series: series

privacy:
  googleAnalytics:
    disable: true

  twitter:
    enableDNT: true

  vimeo:
    enableDNT: true

  youtube:
    privacyEnhanced: true
